version: 2

models:
  - name: dim_customer
    description: "Contains unique customer data."
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: fact_orders
    description: "Fact table containing all order transactions."
    columns:
      - name: order_key
        tests:
          - not_null
          - unique
      - name: sales
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
  - name: dim_product
    description: "contains unique product data."
    columns:
      - name: product_key
        tests:
          - not_null
          - unique
  - name: dim_region
    description: "contains unique region data."
    columns:
      - name: region_key
        tests:
          - not_null
          - unique

